name: IPO Application Scheduler - 8:00 AM

on:
  schedule:
    # Run at 8:00 AM NPT every 24 hours (02:15 UTC)
    - cron: '15 2 * * *'
  workflow_dispatch:
    inputs:
      user_name:
        description: 'User name to apply IPOs for'
        required: true
        default: 'user9'
        type: string

jobs:
  check-ipo-status:
    runs-on: ubuntu-latest
    outputs:
      should_apply: ${{ steps.check-status.outputs.should_apply }}
    steps:
    - name: Check IPO Status
      id: check-status
      run: |
        if [ "${{ vars.APPLY_FOR_TODAY }}" = "true" ]; then
          echo "✅ APPLY_FOR_TODAY is true - proceeding with IPO application"
          echo "should_apply=true" >> $GITHUB_OUTPUT
        else
          echo "❌ APPLY_FOR_TODAY is not true - skipping IPO application"
          echo "should_apply=false" >> $GITHUB_OUTPUT
        fi

  apply-ipos:
    runs-on: ubuntu-latest
    needs: check-ipo-status
    if: needs.check-ipo-status.outputs.should_apply == 'true'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Apply IPOs for user9
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        USER_NAME: ${{ secrets.USER9_NAME }}
      run: |
        python -c "
        import requests
        import os
        import json
        import time
        from datetime import datetime
        
        webhook_url = os.getenv('WEBHOOK_URL')
        telegram_token = os.getenv('TELEGRAM_BOT_TOKEN')
        telegram_chat_id = os.getenv('TELEGRAM_CHAT_ID')
        user_name = os.getenv('USER_NAME')
        
        if not webhook_url:
            print('❌ WEBHOOK_URL not set')
            exit(1)
        
        if not user_name:
            print('❌ USER_NAME not set')
            exit(1)
        
        # Get user name from workflow dispatch or use secret
        input_user_name = '${{ github.event.inputs.user_name }}'
        user_name = input_user_name if input_user_name and input_user_name.strip() else user_name
        
        print(f'🚀 Starting IPO application for user: {user_name}')
        print(f'⏰ Time: {datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")}')
        
        try:
            # Call the webhook with retry mechanism
            max_retries = 3
            retry_delay = 5
            
            for attempt in range(max_retries):
                try:
                    print(f'🔄 Attempt {attempt + 1}/{max_retries}')
                    
                    response = requests.post(
                        f'{webhook_url}/apply',
                        json={'user_name': user_name},
                        headers={'Content-Type': 'application/json'},
                        timeout=(30, 300)  # (connect_timeout, read_timeout)
                    )
                    break  # Success, exit retry loop
                    
                except requests.exceptions.ConnectionError as e:
                    print(f'❌ Connection error on attempt {attempt + 1}: {str(e)}')
                    if attempt < max_retries - 1:
                        print(f'⏳ Retrying in {retry_delay} seconds...')
                        time.sleep(retry_delay)
                        retry_delay *= 2  # Exponential backoff
                    else:
                        raise Exception(f'Connection failed after {max_retries} attempts: {str(e)}')
                        
                except requests.exceptions.Timeout as e:
                    print(f'❌ Timeout error on attempt {attempt + 1}: {str(e)}')
                    if attempt < max_retries - 1:
                        print(f'⏳ Retrying in {retry_delay} seconds...')
                        time.sleep(retry_delay)
                        retry_delay *= 2  # Exponential backoff
                    else:
                        raise Exception(f'Request timeout after {max_retries} attempts: {str(e)}')
                        
                except Exception as e:
                    print(f'❌ Unexpected error on attempt {attempt + 1}: {str(e)}')
                    if attempt < max_retries - 1:
                        print(f'⏳ Retrying in {retry_delay} seconds...')
                        time.sleep(retry_delay)
                        retry_delay *= 2  # Exponential backoff
                    else:
                        raise
            
            print(f'📡 Response Status: {response.status_code}')
            print(f'📡 Response: {response.text}')
            
            if response.status_code == 200:
                result = response.json()
                
                # Check if the response indicates an error
                if result.get('status') == 'error':
                    print(f'❌ IPO application failed: {result.get(\"message\", \"Unknown error\")}')
                    error_msg = f'❌ GitHub Action: IPO Application Failed\n\n'
                    error_msg += f'👤 User: {user_name}\n'
                    error_msg += f'⏰ Time: {datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")}\n'
                    error_msg += f'📄 Error: {result.get(\"message\", \"Unknown error\")}'
                    
                    if telegram_token and telegram_chat_id:
                        telegram_response = requests.post(
                            f'https://api.telegram.org/bot{telegram_token}/sendMessage',
                            json={
                                'chat_id': telegram_chat_id,
                                'text': error_msg,
                                'parse_mode': 'HTML'
                            }
                        )
                        
                        if telegram_response.status_code == 200:
                            print('✅ Telegram error notification sent')
                        else:
                            print(f'❌ Failed to send Telegram error notification: {telegram_response.status_code}')
                else:
                    print('✅ IPO application completed successfully')
                    
                    # Send Telegram notification for success
                    if telegram_token and telegram_chat_id:
                        # Use CDSC name from API response if available, otherwise fallback to user_name
                        cdsc_name = result.get('cdsc_name', user_name)
                        notification = f'🤖 GitHub Action: IPO Application Complete\n\n'
                        notification += f'👤 User: {cdsc_name}\n'
                        notification += f'⏰ Time: {datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")}\n\n'
                        notification += f'📊 Results:\n'
                        notification += f'• Successfully Applied: {result.get(\"total_applied\", 0)}\n'
                        notification += f'• Failed Applications: {result.get(\"total_failed\", 0)}\n'
                        
                        if result.get('applied_issues'):
                            notification += '\n✅ Applied Issues:\n'
                            for issue in result['applied_issues']:
                                notification += f'• {issue[\"scrip\"]} - {issue[\"company\"]}\n'
                        
                        if result.get('failed_issues'):
                            notification += '\n❌ Failed Issues:\n'
                            for issue in result['failed_issues']:
                                notification += f'• {issue[\"scrip\"]} - {issue[\"company\"]} ({issue[\"reason\"]})\n'
                        
                        telegram_response = requests.post(
                            f'https://api.telegram.org/bot{telegram_token}/sendMessage',
                            json={
                                'chat_id': telegram_chat_id,
                                'text': notification,
                                'parse_mode': 'HTML'
                            }
                        )
                        
                        if telegram_response.status_code == 200:
                            print('✅ Telegram notification sent')
                        else:
                            print(f'❌ Failed to send Telegram notification: {telegram_response.status_code}')
                    else:
                        print('⚠️ Telegram credentials not configured')
                    
            else:
                print(f'❌ IPO application failed with status: {response.status_code}')
                error_msg = f'❌ GitHub Action: IPO Application Failed\n\n'
                error_msg += f'👤 User: {user_name}\n'
                error_msg += f'⏰ Time: {datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")}\n'
                error_msg += f'📡 Status: {response.status_code}\n'
                error_msg += f'📄 Response: {response.text}'
                
                if telegram_token and telegram_chat_id:
                    requests.post(
                        f'https://api.telegram.org/bot{telegram_token}/sendMessage',
                        json={
                            'chat_id': telegram_chat_id,
                            'text': error_msg,
                            'parse_mode': 'HTML'
                        }
                    )
                
        except Exception as e:
            print(f'❌ Exception occurred: {str(e)}')
            error_msg = f'❌ GitHub Action: Exception Occurred\n\n'
            error_msg += f'👤 User: {user_name}\n'
            error_msg += f'⏰ Time: {datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")}\n'
            error_msg += f'💥 Error: {str(e)}'
            
            if telegram_token and telegram_chat_id:
                requests.post(
                    f'https://api.telegram.org/bot{telegram_token}/sendMessage',
                    json={
                        'chat_id': telegram_chat_id,
                        'text': error_msg,
                        'parse_mode': 'HTML'
                    }
                )
        " 